### ISSUE TITLE
Authenticate User

### ISSUE THREAD

**Issue by GuillaumeSTEIN** [Atipik/Hoa-WebSocket-Bundle#10]
Hi all,

I'm followed the quick guide on your home page and now I'm trying to authenticate users.
My approche is to send a stringifyed object as message and my php module json_decode it.

I think if I send the session token in the client cookies, I can find the server session.
But I don't know which service in need to inject in my module. 
And I'm not sure if this solution is possible.

If someone as ever tried to do something similar, can you light my way ?

Thx

**Comment by marmotz** [comment]
Hi Guillaume,

WebSocket server do not share session with the reste of symfony application.

We have a similar need in our application and here is how we do:
* on login:
  * we generate a token and save it in a cookie
  * we connect to the WS Server and create a new session with current token (and other infos)
* the site generate a page (with angular application), read cookie, create a connection to WS Server and send a login request with token
* on WS Server:
  * when we receive a new session request, we save token in memory
  * when we receive a login request, we check token

This bundle allow you to use bisically WebSocket.
We have extended this bundle to allow named request with data.
This is very basic: a name, some parameters, all is encapsulated in a json object.
That's why i talk about "new session request" and "login request"
